import type { Context } from "@soniox/speech-to-text-web";

import { sanitizeExtraTerms } from "@/lib/session-settings";

type StructuredContext = Exclude<Context, string>;

const GENERAL_CONTEXT = [
  { key: "domain", value: "Healthcare" },
  { key: "topic", value: "Online medical consultation" },
] as const;

const LEGACY_CONTEXT_TERMS = [
  "オンライン診療",
  "既往歴",
  "処方薬",
  "アレルギー",
  "バイタルサイン",
] as const;

export const MEDICAL_TERMS = [
  // Commonly encountered medicines and active ingredients.
  "ブスコパン",
  "ロキソニン",
  "カロナール",
  "ガスター",
  "ムコダイン",
  "メジコン",
  "PL配合顆粒",
  "タミフル",
  "リレンザ",
  "イナビル",
  "ゾフルーザ",
  "アレグラ",
  "クラリチン",
  "ザイザル",
  "タリオン",
  "サワシリン",
  "オーグメンチン",
  "クラリス",
  "ジスロマック",
  "フロモックス",
  "セフゾン",
  "ミノマイシン",
  "ボルタレン",
  "セレコックス",
  "バファリン",
  "ポンタール",
  "プレドニン",
  "リンデロン",
  "メプチン",
  "ホクナリン",
  "シムビコート",
  "アドエア",
  "キプレス",
  "シングレア",
  "ネキシウム",
  "タケキャブ",
  "プロマック",
  "マグミット",
  "モビコール",
  "ビオフェルミン",
  "ミヤBM",
  "ナウゼリン",
  "プリンペラン",
  "アムロジン",
  "ノルバスク",
  "ディオバン",
  "ミカルディス",
  "メトグルコ",
  "リピトール",
  "クレストール",
  "ワーファリン",
  "エリキュース",
  "バイアスピリン",
  "プラビックス",
  "ランタス",
  "ヒューマログ",
  "エピペン",
  "ロキソプロフェン",
  "アセトアミノフェン",
  "イブプロフェン",
  "アモキシシリン",
  "アジスロマイシン",
  "クラリスロマイシン",
  "セフジニル",
  "セフカペンピボキシル",
  "レボフロキサシン",
  "オセルタミビル",
  "ラニナミビル",
  "バロキサビル",
  "カルボシステイン",
  "デキストロメトルファン",
  "アンブロキソール",
  "ファモチジン",
  "エソメプラゾール",
  "ボノプラザン",
  "ドンペリドン",
  "メトクロプラミド",
  "アムロジピン",
  "カンデサルタン",
  "テルミサルタン",
  "メトホルミン",
  "アトルバスタチン",
  "ロスバスタチン",
  "プレドニゾロン",
  "ベタメタゾン",
  "サルブタモール",
  "モンテルカスト",
  "フェキソフェナジン",
  "ロラタジン",
  "レボセチリジン",
  "エピナスチン",
  "ブチルスコポラミン",
  // Symptoms and findings frequently discussed in general practice.
  "発熱",
  "微熱",
  "悪寒",
  "倦怠感",
  "頭痛",
  "めまい",
  "立ちくらみ",
  "咳",
  "痰",
  "鼻水",
  "鼻づまり",
  "咽頭痛",
  "息切れ",
  "呼吸困難",
  "喘鳴",
  "動悸",
  "胸痛",
  "腹痛",
  "心窩部痛",
  "吐き気",
  "嘔吐",
  "下痢",
  "便秘",
  "血便",
  "食欲不振",
  "体重減少",
  "浮腫",
  "発疹",
  "じんましん",
  "かゆみ",
  "関節痛",
  "腰痛",
  "しびれ",
  "不眠",
  "口渇",
  "頻尿",
  "排尿痛",
  "血尿",
  "生理痛",
  "月経不順",
  // Consultation, examination, and test vocabulary.
  "問診",
  "視診",
  "触診",
  "聴診",
  "打診",
  "主訴",
  "現病歴",
  "既往歴",
  "家族歴",
  "服薬歴",
  "処方薬",
  "市販薬",
  "アレルギー",
  "副作用",
  "血圧",
  "脈拍",
  "体温",
  "呼吸数",
  "酸素飽和度",
  "バイタルサイン",
  "心電図",
  "レントゲン",
  "超音波検査",
  "内視鏡検査",
  "採血",
  "血液検査",
  "尿検査",
  "便潜血検査",
  "抗原検査",
  "PCR検査",
  "CT検査",
  "MRI検査",
  "血糖値",
  "HbA1c",
  "白血球",
  "赤血球",
  "血小板",
  "ヘモグロビン",
  "CRP",
  "肝機能",
  "腎機能",
  "処方箋",
  "用法用量",
  "食前",
  "食後",
  "頓服",
  "経過観察",
  "再診",
  "紹介状",
  "診断書",
] as const;

export const MEDICAL_TRANSLATION_TERMS = [
  { source: "ブスコパン", target: "Buscopan" },
  { source: "ロキソニン", target: "Loxonin" },
  { source: "カロナール", target: "Calonal" },
  { source: "ガスター", target: "Gaster" },
  { source: "ムコダイン", target: "Mucodyne" },
  { source: "メジコン", target: "Medicon" },
  { source: "PL配合顆粒", target: "PL Combination Granules" },
  { source: "タミフル", target: "Tamiflu" },
  { source: "リレンザ", target: "Relenza" },
  { source: "イナビル", target: "Inavir" },
  { source: "ゾフルーザ", target: "Xofluza" },
  { source: "アレグラ", target: "Allegra" },
  { source: "クラリチン", target: "Claritin" },
  { source: "ザイザル", target: "Xyzal" },
  { source: "オーグメンチン", target: "Augmentin" },
  { source: "ジスロマック", target: "Zithromax" },
  { source: "ボルタレン", target: "Voltaren" },
  { source: "セレコックス", target: "Celecox" },
  { source: "シムビコート", target: "Symbicort" },
  { source: "ネキシウム", target: "Nexium" },
  { source: "ロキソプロフェン", target: "loxoprofen" },
  { source: "アセトアミノフェン", target: "acetaminophen" },
  { source: "イブプロフェン", target: "ibuprofen" },
  { source: "アモキシシリン", target: "amoxicillin" },
  { source: "アジスロマイシン", target: "azithromycin" },
  { source: "クラリスロマイシン", target: "clarithromycin" },
  { source: "セフジニル", target: "cefdinir" },
  { source: "レボフロキサシン", target: "levofloxacin" },
  { source: "オセルタミビル", target: "oseltamivir" },
  { source: "カルボシステイン", target: "carbocisteine" },
  { source: "デキストロメトルファン", target: "dextromethorphan" },
  { source: "アンブロキソール", target: "ambroxol" },
  { source: "ファモチジン", target: "famotidine" },
  { source: "エソメプラゾール", target: "esomeprazole" },
  { source: "ボノプラザン", target: "vonoprazan" },
  { source: "ドンペリドン", target: "domperidone" },
  { source: "メトクロプラミド", target: "metoclopramide" },
  { source: "アムロジピン", target: "amlodipine" },
  { source: "メトホルミン", target: "metformin" },
  { source: "プレドニゾロン", target: "prednisolone" },
  { source: "モンテルカスト", target: "montelukast" },
  { source: "フェキソフェナジン", target: "fexofenadine" },
] as const satisfies readonly { source: string; target: string }[];

export function buildMedicalContext(
  extraTerms: readonly string[] = [],
): StructuredContext {
  return {
    general: GENERAL_CONTEXT.map((entry) => ({ ...entry })),
    terms: [
      ...new Set([
        ...LEGACY_CONTEXT_TERMS,
        ...MEDICAL_TERMS,
        ...sanitizeExtraTerms(extraTerms),
      ]),
    ],
    translation_terms: MEDICAL_TRANSLATION_TERMS.map((term) => ({ ...term })),
  };
}
